// models/Admin.js
// ─────────────────────────────────────────────────────────────────────────────
// Admin Model for DreamyCrochet05
// Stores the single admin account with a securely hashed password in MongoDB.
// Only one admin account is ever needed — created via `node seedAdmin.js`.
// ─────────────────────────────────────────────────────────────────────────────

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const adminSchema = new mongoose.Schema({
  // Admin's email address — used for login (stored in .env, never in code)
  email: {
    type: String,
    required: [true, 'Admin email is required'],
    unique: true,
    lowercase: true,
    trim: true
  },

  // Hashed password — plain text is NEVER stored here
  // bcrypt hash is generated by the pre-save hook below
  password: {
    type: String,
    required: [true, 'Admin password is required'],
    minlength: 6
  },

  // Timestamp of account creation
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// ─── PRE-SAVE HOOK ────────────────────────────────────────────────────────────
// Before saving to MongoDB, automatically hash the password if it was modified.
// This means: plain text password goes IN, bcrypt hash is what gets stored.
adminSchema.pre('save', async function (next) {
  // Only re-hash if password field was actually changed (prevents double-hashing)
  if (!this.isModified('password')) return next();

  try {
    // Salt rounds = 12 (higher = more secure, but slower)
    const salt = await bcrypt.genSalt(12);
    this.password = await bcrypt.hash(this.password, salt);
    next();
  } catch (err) {
    next(err);
  }
});

// ─── INSTANCE METHOD: comparePassword ────────────────────────────────────────
// Safely compares a plain-text candidate password against the stored bcrypt hash.
// Usage: const isMatch = await admin.comparePassword(enteredPassword);
adminSchema.methods.comparePassword = async function (candidatePassword) {
  return bcrypt.compare(candidatePassword, this.password);
};

module.exports = mongoose.model('Admin', adminSchema);
